---
- name: RouterOS arp
  hosts: all
  gather_facts: true
  tasks:
    - name: Change Arp timeout
      routeros_command:
        commands: /ip dhcp-server/set lease-script="delay 10000ms; ip arp remove [find where !mac-address and !complete]" numbers=0
