---
- name: Send file to MikroTik via FTP
  hosts: all
  gather_facts: no


  tasks:
    - name: Upload files
      net_put:
        src: ../Keys/badm.pub
        dest: /{{inventory_hostname}}_ssh.pub
        protocol: sftp

    - name: Upload files
      net_put:
        src: ../Keys/badm_key
        dest: /{{inventory_hostname}}_sshkey
        protocol: sftp

    - name: import hostkey
      routeros_command:
        commands:
          - /user ssh-keys import public-key-file={{inventory_hostname}}_ssh.pub user=badm
          -
# key-owner=badm
