---
- name: RouterOS remove address list
  hosts: all
  gather_facts: true
  tasks:

    - name: Gather system resources
      community.routeros.command:
        commands:
          - /ip fi address-list remove [find list=direct]
      register: remove_address

    - name: Show system resources
      debug:
        var: remove_address.stdout_lines
