---
- name: RouterOS test
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather system resources
      community.routeros.command:
        commands:
          - /system resource print
      register: address_list_print

    - name: Show system resources
      debug:
        var: address_list_print.stdout_lines


    - name: Gather facts
      community.routeros.facts:

    - name: run multiple commands on remote nodes
      routeros_command:
        commands:
          - /system routerboard print
          - /system identity print

