---
- name: RouterOS test
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather system resources
      community.routeros.command:
        commands:
          - /system resource print
      register: address_list_print

#    - name: Save result to file
#      copy:
#        content: "{{ address_list_print.stdout }}"
#        dest: ../Data/result
#      delegate_to: localhost

    - name: Show system resources
      debug:
        var: address_list_print.stdout_lines

#
#    - name: Gather facts
#      community.routeros.facts:

#    - name: run multiple commands on remote nodes
#      routeros_command:
#        commands:
#          - /system routerboard print
#          - /system identity print

