version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always

    ports:
      - "8767:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf:ro
