kubectl get node
kubectl get pods
kubectl run hello --generator=run-pod/v1 --image=registry.thebull.ru:latest --port=80
kubectl delete pods hello
kubectl describe pods hello - полная информация пода
kubectl exec hello date
kubectl exec -it hello sh - вход в под командная консоль
kubectl logs hello 
kubectl port-forward hello 7788:80 - 7788 это порт наружу
kubectl apply -f my-web-service.yaml - создание пода из файла
kubectl get svc -n ingress-nginx - просмотр портов и ip nginx ingress
kubectl logs fastapi-deployment-647cb6bc79-brsqz

kubectl get ingress fastapi-ingress
kubectl delete deployment postgres-deployment
kubectl logs -l app=fastapi --tail=50
kubectl get ingress
